version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api.Dockerfile
      args:
        POLAR_DOCKER_DEV: ${POLAR_DOCKER_DEV-false}
    command: uvicorn polar.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./polar/:/polar/
    ports:
      - 8002:8000
