version: '3.8'

services:
  db:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_USER=${POLAR_POSTGRES_USER}
      - POSTGRES_PASSWORD=${POLAR_POSTGRES_PWD}
      - POSTGRES_DB=${POLAR_POSTGRES_DB}
      - POSTGRES_PORT=${POLAR_POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POLAR_POSTGRES_PORT}:${POLAR_POSTGRES_PORT}"
    expose:
      - ${POLAR_POSTGRES_PORT}
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POLAR_POSTGRES_DB}", "-U", "${POLAR_POSTGRES_USER}" ]
      timeout: 40s
      interval: 2s
      retries: 20

volumes:
  postgres_data: