name: Test Server 🐍

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.3.2"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:15.1-bullseye
        env:
          POSTGRES_USER: polar
          POSTGRES_PASSWORD: polar
          POSTGRES_DB: polar_test
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redislabs/redismod
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: 🔧 poetry install
        working-directory: ./server
        run: poetry install --no-root
      - name: 🐍 Run tests
        working-directory: ./server
        env:
          POLAR_POSTGRES_HOST: postgres
          POLAR_REDIS_HOST: redis
          POLAR_CELERY_BROKER_URL: "redis://redis:6379"
          POLAR_CELERY_BACKEND_URL: "redis://redis:6379"

        run: poetry run pytest
